# Generated by Django 2.1.4 on 2019-02-27 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ISGMStore', '0002_purchase_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.ImageField(default=None, upload_to=''),
        ),
    ]
