# Generated by Django 2.1.4 on 2019-03-08 08:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ISGMStore', '0005_auto_20190301_0720'),
    ]

    operations = [
        migrations.CreateModel(
            name='confirmed_order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='order_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('original_price', models.FloatField(default=0)),
                ('discount', models.FloatField(default=0)),
                ('confirmed_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ISGMStore.confirmed_order')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ISGMStore.item')),
            ],
        ),
        migrations.RemoveField(
            model_name='purchase_order',
            name='item',
        ),
        migrations.RemoveField(
            model_name='purchase_order',
            name='user',
        ),
        migrations.DeleteModel(
            name='purchase_order',
        ),
    ]
