# Generated by Django 2.1.4 on 2019-04-23 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ISGMStore', '0006_auto_20190308_0842'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_history',
            name='order_status',
            field=models.CharField(choices=[('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('delivered', 'Delivered')], default='confirmed', max_length=20),
        ),
    ]
