# Generated by Django 2.2.1 on 2019-08-06 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ISGMStore', '0008_remove_customer_credits'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image_back',
            field=models.ImageField(default=None, upload_to='ISGMStore/images/back/'),
        ),
        migrations.AddField(
            model_name='item',
            name='item_image_side',
            field=models.ImageField(default=None, upload_to='ISGMStore/images/side/'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_image',
            field=models.ImageField(default=None, upload_to='ISGMStore/images/center/'),
        ),
    ]
